export var json = {
  "nodes": [
  {"id": "Myriel"},
  {"id": "Napoleon"},
  {"id": "Mlle.Baptistine"},
  {"id": "Mme.Magloire"},
  {"id": "CountessdeLo"},
  {"id": "Geborand"},
  {"id": "Champtercier"},
  {"id": "Cravatte"},
  {"id": "Count"},
  {"id": "OldMan"},
  {"id": "Labarre"},
  {"id": "Valjean"},
  {"id": "Marguerite"},
  {"id": "Mme.deR"},
  {"id": "Isabeau"},
  {"id": "Gervais"},
  {"id": "Tholomyes"},
  {"id": "Listolier"},
  {"id": "Fameuil"},
  {"id": "Blacheville"},
  {"id": "Favourite"},
  {"id": "Dahlia"},
  {"id": "Zephine"},
  {"id": "Fantine"},
  {"id": "Mme.Thenardier"},
  {"id": "Thenardier"},
  {"id": "Cosette"},
  {"id": "Javert"},
  {"id": "Fauchelevent"},
  {"id": "Bamatabois"},
  {"id": "Perpetue"},
  {"id": "Simplice"},
  {"id": "Scaufflaire"},
  {"id": "Woman1"},
  {"id": "Judge"},
  {"id": "Champmathieu"},
  {"id": "Brevet"},
  {"id": "Chenildieu"},
  {"id": "Cochepaille"},
  {"id": "Pontmercy"},
  {"id": "Boulatruelle"},
  {"id": "Eponine"},
  {"id": "Anzelma"},
  {"id": "Woman2"},
  {"id": "MotherInnocent"},
  {"id": "Gribier"},
  {"id": "Jondrette"},
  {"id": "Mme.Burgon"},
  {"id": "Gavroche"},
  {"id": "Gillenormand"},
  {"id": "Magnon"},
  {"id": "Mlle.Gillenormand"},
  {"id": "Mme.Pontmercy"},
  {"id": "Mlle.Vaubois"},
  {"id": "Lt.Gillenormand"},
  {"id": "Marius"},
  {"id": "BaronessT"},
  {"id": "Mabeuf"},
  {"id": "Enjolras"},
  {"id": "Combeferre"},
  {"id": "Prouvaire"},
  {"id": "Feuilly"},
  {"id": "Courfeyrac"},
  {"id": "Bahorel"},
  {"id": "Bossuet"},
  {"id": "Joly"},
  {"id": "Grantaire"},
  {"id": "MotherPlutarch"},
  {"id": "Gueulemer"},
  {"id": "Babet"},
  {"id": "Claquesous"},
  {"id": "Montparnasse"},
  {"id": "Toussaint"},
  {"id": "Child1"},
  {"id": "Child2"},
  {"id": "Brujon"},
  {"id": "Mme.Hucheloup"}
],
  "links": [
  {"source": "Napoleon", "target": "Myriel", "distance": 1},
  {"source": "Mlle.Baptistine", "target": "Myriel", "distance": 8},
  {"source": "Mme.Magloire", "target": "Myriel", "distance": 10},
  {"source": "Mme.Magloire", "target": "Mlle.Baptistine", "distance": 6},
  {"source": "CountessdeLo", "target": "Myriel", "distance": 1},
  {"source": "Geborand", "target": "Myriel", "distance": 1},
  {"source": "Champtercier", "target": "Myriel", "distance": 1},
  {"source": "Cravatte", "target": "Myriel", "distance": 1},
  {"source": "Count", "target": "Myriel", "distance": 2},
  {"source": "OldMan", "target": "Myriel", "distance": 1},
  {"source": "Valjean", "target": "Labarre", "distance": 1},
  {"source": "Valjean", "target": "Mme.Magloire", "distance": 3},
  {"source": "Valjean", "target": "Mlle.Baptistine", "distance": 3},
  {"source": "Valjean", "target": "Myriel", "distance": 5},
  {"source": "Marguerite", "target": "Valjean", "distance": 1},
  {"source": "Mme.deR", "target": "Valjean", "distance": 1},
  {"source": "Isabeau", "target": "Valjean", "distance": 1},
  {"source": "Gervais", "target": "Valjean", "distance": 1},
  {"source": "Listolier", "target": "Tholomyes", "distance": 4},
  {"source": "Fameuil", "target": "Tholomyes", "distance": 4},
  {"source": "Fameuil", "target": "Listolier", "distance": 4},
  {"source": "Blacheville", "target": "Tholomyes", "distance": 4},
  {"source": "Blacheville", "target": "Listolier", "distance": 4},
  {"source": "Blacheville", "target": "Fameuil", "distance": 4},
  {"source": "Favourite", "target": "Tholomyes", "distance": 3},
  {"source": "Favourite", "target": "Listolier", "distance": 3},
  {"source": "Favourite", "target": "Fameuil", "distance": 3},
  {"source": "Favourite", "target": "Blacheville", "distance": 4},
  {"source": "Dahlia", "target": "Tholomyes", "distance": 3},
  {"source": "Dahlia", "target": "Listolier", "distance": 3},
  {"source": "Dahlia", "target": "Fameuil", "distance": 3},
  {"source": "Dahlia", "target": "Blacheville", "distance": 3},
  {"source": "Dahlia", "target": "Favourite", "distance": 5},
  {"source": "Zephine", "target": "Tholomyes", "distance": 3},
  {"source": "Zephine", "target": "Listolier", "distance": 3},
  {"source": "Zephine", "target": "Fameuil", "distance": 3},
  {"source": "Zephine", "target": "Blacheville", "distance": 3},
  {"source": "Zephine", "target": "Favourite", "distance": 4},
  {"source": "Zephine", "target": "Dahlia", "distance": 4},
  {"source": "Fantine", "target": "Tholomyes", "distance": 3},
  {"source": "Fantine", "target": "Listolier", "distance": 3},
  {"source": "Fantine", "target": "Fameuil", "distance": 3},
  {"source": "Fantine", "target": "Blacheville", "distance": 3},
  {"source": "Fantine", "target": "Favourite", "distance": 4},
  {"source": "Fantine", "target": "Dahlia", "distance": 4},
  {"source": "Fantine", "target": "Zephine", "distance": 4},
  {"source": "Fantine", "target": "Marguerite", "distance": 2},
  {"source": "Fantine", "target": "Valjean", "distance": 9},
  {"source": "Mme.Thenardier", "target": "Fantine", "distance": 2},
  {"source": "Mme.Thenardier", "target": "Valjean", "distance": 7},
  {"source": "Thenardier", "target": "Mme.Thenardier", "distance": 13},
  {"source": "Thenardier", "target": "Fantine", "distance": 1},
  {"source": "Thenardier", "target": "Valjean", "distance": 12},
  {"source": "Cosette", "target": "Mme.Thenardier", "distance": 4},
  {"source": "Cosette", "target": "Valjean", "distance": 31},
  {"source": "Cosette", "target": "Tholomyes", "distance": 1},
  {"source": "Cosette", "target": "Thenardier", "distance": 1},
  {"source": "Javert", "target": "Valjean", "distance": 17},
  {"source": "Javert", "target": "Fantine", "distance": 5},
  {"source": "Javert", "target": "Thenardier", "distance": 5},
  {"source": "Javert", "target": "Mme.Thenardier", "distance": 1},
  {"source": "Javert", "target": "Cosette", "distance": 1},
  {"source": "Fauchelevent", "target": "Valjean", "distance": 8},
  {"source": "Fauchelevent", "target": "Javert", "distance": 1},
  {"source": "Bamatabois", "target": "Fantine", "distance": 1},
  {"source": "Bamatabois", "target": "Javert", "distance": 1},
  {"source": "Bamatabois", "target": "Valjean", "distance": 2},
  {"source": "Perpetue", "target": "Fantine", "distance": 1},
  {"source": "Simplice", "target": "Perpetue", "distance": 2},
  {"source": "Simplice", "target": "Valjean", "distance": 3},
  {"source": "Simplice", "target": "Fantine", "distance": 2},
  {"source": "Simplice", "target": "Javert", "distance": 1},
  {"source": "Scaufflaire", "target": "Valjean", "distance": 1},
  {"source": "Woman1", "target": "Valjean", "distance": 2},
  {"source": "Woman1", "target": "Javert", "distance": 1},
  {"source": "Judge", "target": "Valjean", "distance": 3},
  {"source": "Judge", "target": "Bamatabois", "distance": 2},
  {"source": "Champmathieu", "target": "Valjean", "distance": 3},
  {"source": "Champmathieu", "target": "Judge", "distance": 3},
  {"source": "Champmathieu", "target": "Bamatabois", "distance": 2},
  {"source": "Brevet", "target": "Judge", "distance": 2},
  {"source": "Brevet", "target": "Champmathieu", "distance": 2},
  {"source": "Brevet", "target": "Valjean", "distance": 2},
  {"source": "Brevet", "target": "Bamatabois", "distance": 1},
  {"source": "Chenildieu", "target": "Judge", "distance": 2},
  {"source": "Chenildieu", "target": "Champmathieu", "distance": 2},
  {"source": "Chenildieu", "target": "Brevet", "distance": 2},
  {"source": "Chenildieu", "target": "Valjean", "distance": 2},
  {"source": "Chenildieu", "target": "Bamatabois", "distance": 1},
  {"source": "Cochepaille", "target": "Judge", "distance": 2},
  {"source": "Cochepaille", "target": "Champmathieu", "distance": 2},
  {"source": "Cochepaille", "target": "Brevet", "distance": 2},
  {"source": "Cochepaille", "target": "Chenildieu", "distance": 2},
  {"source": "Cochepaille", "target": "Valjean", "distance": 2},
  {"source": "Cochepaille", "target": "Bamatabois", "distance": 1},
  {"source": "Pontmercy", "target": "Thenardier", "distance": 1},
  {"source": "Boulatruelle", "target": "Thenardier", "distance": 1},
  {"source": "Eponine", "target": "Mme.Thenardier", "distance": 2},
  {"source": "Eponine", "target": "Thenardier", "distance": 3},
  {"source": "Anzelma", "target": "Eponine", "distance": 2},
  {"source": "Anzelma", "target": "Thenardier", "distance": 2},
  {"source": "Anzelma", "target": "Mme.Thenardier", "distance": 1},
  {"source": "Woman2", "target": "Valjean", "distance": 3},
  {"source": "Woman2", "target": "Cosette", "distance": 1},
  {"source": "Woman2", "target": "Javert", "distance": 1},
  {"source": "MotherInnocent", "target": "Fauchelevent", "distance": 3},
  {"source": "MotherInnocent", "target": "Valjean", "distance": 1},
  {"source": "Gribier", "target": "Fauchelevent", "distance": 2},
  {"source": "Mme.Burgon", "target": "Jondrette", "distance": 1},
  {"source": "Gavroche", "target": "Mme.Burgon", "distance": 2},
  {"source": "Gavroche", "target": "Thenardier", "distance": 1},
  {"source": "Gavroche", "target": "Javert", "distance": 1},
  {"source": "Gavroche", "target": "Valjean", "distance": 1},
  {"source": "Gillenormand", "target": "Cosette", "distance": 3},
  {"source": "Gillenormand", "target": "Valjean", "distance": 2},
  {"source": "Magnon", "target": "Gillenormand", "distance": 1},
  {"source": "Magnon", "target": "Mme.Thenardier", "distance": 1},
  {"source": "Mlle.Gillenormand", "target": "Gillenormand", "distance": 9},
  {"source": "Mlle.Gillenormand", "target": "Cosette", "distance": 2},
  {"source": "Mlle.Gillenormand", "target": "Valjean", "distance": 2},
  {"source": "Mme.Pontmercy", "target": "Mlle.Gillenormand", "distance": 1},
  {"source": "Mme.Pontmercy", "target": "Pontmercy", "distance": 1},
  {"source": "Mlle.Vaubois", "target": "Mlle.Gillenormand", "distance": 1},
  {"source": "Lt.Gillenormand", "target": "Mlle.Gillenormand", "distance": 2},
  {"source": "Lt.Gillenormand", "target": "Gillenormand", "distance": 1},
  {"source": "Lt.Gillenormand", "target": "Cosette", "distance": 1},
  {"source": "Marius", "target": "Mlle.Gillenormand", "distance": 6},
  {"source": "Marius", "target": "Gillenormand", "distance": 12},
  {"source": "Marius", "target": "Pontmercy", "distance": 1},
  {"source": "Marius", "target": "Lt.Gillenormand", "distance": 1},
  {"source": "Marius", "target": "Cosette", "distance": 21},
  {"source": "Marius", "target": "Valjean", "distance": 19},
  {"source": "Marius", "target": "Tholomyes", "distance": 1},
  {"source": "Marius", "target": "Thenardier", "distance": 2},
  {"source": "Marius", "target": "Eponine", "distance": 5},
  {"source": "Marius", "target": "Gavroche", "distance": 4},
  {"source": "BaronessT", "target": "Gillenormand", "distance": 1},
  {"source": "BaronessT", "target": "Marius", "distance": 1},
  {"source": "Mabeuf", "target": "Marius", "distance": 1},
  {"source": "Mabeuf", "target": "Eponine", "distance": 1},
  {"source": "Mabeuf", "target": "Gavroche", "distance": 1},
  {"source": "Enjolras", "target": "Marius", "distance": 7},
  {"source": "Enjolras", "target": "Gavroche", "distance": 7},
  {"source": "Enjolras", "target": "Javert", "distance": 6},
  {"source": "Enjolras", "target": "Mabeuf", "distance": 1},
  {"source": "Enjolras", "target": "Valjean", "distance": 4},
  {"source": "Combeferre", "target": "Enjolras", "distance": 15},
  {"source": "Combeferre", "target": "Marius", "distance": 5},
  {"source": "Combeferre", "target": "Gavroche", "distance": 6},
  {"source": "Combeferre", "target": "Mabeuf", "distance": 2},
  {"source": "Prouvaire", "target": "Gavroche", "distance": 1},
  {"source": "Prouvaire", "target": "Enjolras", "distance": 4},
  {"source": "Prouvaire", "target": "Combeferre", "distance": 2},
  {"source": "Feuilly", "target": "Gavroche", "distance": 2},
  {"source": "Feuilly", "target": "Enjolras", "distance": 6},
  {"source": "Feuilly", "target": "Prouvaire", "distance": 2},
  {"source": "Feuilly", "target": "Combeferre", "distance": 5},
  {"source": "Feuilly", "target": "Mabeuf", "distance": 1},
  {"source": "Feuilly", "target": "Marius", "distance": 1},
  {"source": "Courfeyrac", "target": "Marius", "distance": 9},
  {"source": "Courfeyrac", "target": "Enjolras", "distance": 17},
  {"source": "Courfeyrac", "target": "Combeferre", "distance": 13},
  {"source": "Courfeyrac", "target": "Gavroche", "distance": 7},
  {"source": "Courfeyrac", "target": "Mabeuf", "distance": 2},
  {"source": "Courfeyrac", "target": "Eponine", "distance": 1},
  {"source": "Courfeyrac", "target": "Feuilly", "distance": 6},
  {"source": "Courfeyrac", "target": "Prouvaire", "distance": 3},
  {"source": "Bahorel", "target": "Combeferre", "distance": 5},
  {"source": "Bahorel", "target": "Gavroche", "distance": 5},
  {"source": "Bahorel", "target": "Courfeyrac", "distance": 6},
  {"source": "Bahorel", "target": "Mabeuf", "distance": 2},
  {"source": "Bahorel", "target": "Enjolras", "distance": 4},
  {"source": "Bahorel", "target": "Feuilly", "distance": 3},
  {"source": "Bahorel", "target": "Prouvaire", "distance": 2},
  {"source": "Bahorel", "target": "Marius", "distance": 1},
  {"source": "Bossuet", "target": "Marius", "distance": 5},
  {"source": "Bossuet", "target": "Courfeyrac", "distance": 12},
  {"source": "Bossuet", "target": "Gavroche", "distance": 5},
  {"source": "Bossuet", "target": "Bahorel", "distance": 4},
  {"source": "Bossuet", "target": "Enjolras", "distance": 10},
  {"source": "Bossuet", "target": "Feuilly", "distance": 6},
  {"source": "Bossuet", "target": "Prouvaire", "distance": 2},
  {"source": "Bossuet", "target": "Combeferre", "distance": 9},
  {"source": "Bossuet", "target": "Mabeuf", "distance": 1},
  {"source": "Bossuet", "target": "Valjean", "distance": 1},
  {"source": "Joly", "target": "Bahorel", "distance": 5},
  {"source": "Joly", "target": "Bossuet", "distance": 7},
  {"source": "Joly", "target": "Gavroche", "distance": 3},
  {"source": "Joly", "target": "Courfeyrac", "distance": 5},
  {"source": "Joly", "target": "Enjolras", "distance": 5},
  {"source": "Joly", "target": "Feuilly", "distance": 5},
  {"source": "Joly", "target": "Prouvaire", "distance": 2},
  {"source": "Joly", "target": "Combeferre", "distance": 5},
  {"source": "Joly", "target": "Mabeuf", "distance": 1},
  {"source": "Joly", "target": "Marius", "distance": 2},
  {"source": "Grantaire", "target": "Bossuet", "distance": 3},
  {"source": "Grantaire", "target": "Enjolras", "distance": 3},
  {"source": "Grantaire", "target": "Combeferre", "distance": 1},
  {"source": "Grantaire", "target": "Courfeyrac", "distance": 2},
  {"source": "Grantaire", "target": "Joly", "distance": 2},
  {"source": "Grantaire", "target": "Gavroche", "distance": 1},
  {"source": "Grantaire", "target": "Bahorel", "distance": 1},
  {"source": "Grantaire", "target": "Feuilly", "distance": 1},
  {"source": "Grantaire", "target": "Prouvaire", "distance": 1},
  {"source": "MotherPlutarch", "target": "Mabeuf", "distance": 3},
  {"source": "Gueulemer", "target": "Thenardier", "distance": 5},
  {"source": "Gueulemer", "target": "Valjean", "distance": 1},
  {"source": "Gueulemer", "target": "Mme.Thenardier", "distance": 1},
  {"source": "Gueulemer", "target": "Javert", "distance": 1},
  {"source": "Gueulemer", "target": "Gavroche", "distance": 1},
  {"source": "Gueulemer", "target": "Eponine", "distance": 1},
  {"source": "Babet", "target": "Thenardier", "distance": 6},
  {"source": "Babet", "target": "Gueulemer", "distance": 6},
  {"source": "Babet", "target": "Valjean", "distance": 1},
  {"source": "Babet", "target": "Mme.Thenardier", "distance": 1},
  {"source": "Babet", "target": "Javert", "distance": 2},
  {"source": "Babet", "target": "Gavroche", "distance": 1},
  {"source": "Babet", "target": "Eponine", "distance": 1},
  {"source": "Claquesous", "target": "Thenardier", "distance": 4},
  {"source": "Claquesous", "target": "Babet", "distance": 4},
  {"source": "Claquesous", "target": "Gueulemer", "distance": 4},
  {"source": "Claquesous", "target": "Valjean", "distance": 1},
  {"source": "Claquesous", "target": "Mme.Thenardier", "distance": 1},
  {"source": "Claquesous", "target": "Javert", "distance": 1},
  {"source": "Claquesous", "target": "Eponine", "distance": 1},
  {"source": "Claquesous", "target": "Enjolras", "distance": 1},
  {"source": "Montparnasse", "target": "Javert", "distance": 1},
  {"source": "Montparnasse", "target": "Babet", "distance": 2},
  {"source": "Montparnasse", "target": "Gueulemer", "distance": 2},
  {"source": "Montparnasse", "target": "Claquesous", "distance": 2},
  {"source": "Montparnasse", "target": "Valjean", "distance": 1},
  {"source": "Montparnasse", "target": "Gavroche", "distance": 1},
  {"source": "Montparnasse", "target": "Eponine", "distance": 1},
  {"source": "Montparnasse", "target": "Thenardier", "distance": 1},
  {"source": "Toussaint", "target": "Cosette", "distance": 2},
  {"source": "Toussaint", "target": "Javert", "distance": 1},
  {"source": "Toussaint", "target": "Valjean", "distance": 1},
  {"source": "Child1", "target": "Gavroche", "distance": 2},
  {"source": "Child2", "target": "Gavroche", "distance": 2},
  {"source": "Child2", "target": "Child1", "distance": 3},
  {"source": "Brujon", "target": "Babet", "distance": 3},
  {"source": "Brujon", "target": "Gueulemer", "distance": 3},
  {"source": "Brujon", "target": "Thenardier", "distance": 3},
  {"source": "Brujon", "target": "Gavroche", "distance": 1},
  {"source": "Brujon", "target": "Eponine", "distance": 1},
  {"source": "Brujon", "target": "Claquesous", "distance": 1},
  {"source": "Brujon", "target": "Montparnasse", "distance": 1},
  {"source": "Mme.Hucheloup", "target": "Bossuet", "distance": 1},
  {"source": "Mme.Hucheloup", "target": "Joly", "distance": 1},
  {"source": "Mme.Hucheloup", "target": "Grantaire", "distance": 1},
  {"source": "Mme.Hucheloup", "target": "Bahorel", "distance": 1},
  {"source": "Mme.Hucheloup", "target": "Courfeyrac", "distance": 1},
  {"source": "Mme.Hucheloup", "target": "Gavroche", "distance": 1},
  {"source": "Mme.Hucheloup", "target": "Enjolras", "distance": 1}
]
};
