export const configFileConstants = {
    GET_CONFIGFILE_REQUEST: 'GET_CONFIGFILE_REQUEST',
    GET_CONFIGFILE_SUCCESS: 'GET_CONFIGFILE_SUCCESS',
    GET_CONFIGFILE_FAILURE: 'GET_CONFIGFILE_FAILURE',

    INVALIDATE_CONFIGFILE_CACHE: 'INVALIDATE_CONFIGFILE_CACHE'
};
