export const teamConstants = {
  CREATE_REQUEST: 'TEAMS_CREATE_REQUEST',
  CREATE_SUCCESS: 'TEAMS_CREATE_SUCCESS',
  CREATE_FAILURE: 'TEAMS_CREATE_FAILURE',

  GETALL_REQUEST: 'TEAMS_GETALL_REQUEST',
  GETALL_SUCCESS: 'TEAMS_GETALL_SUCCESS',
  GETALL_FAILURE: 'TEAMS_GETALL_FAILURE',

  UPDATE_REQUEST: 'TEAMS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'TEAMS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'TEAMS_UPDATE_FAILURE',

  DELETE_REQUEST: 'TEAMS_DELETE_REQUEST',
  DELETE_SUCCESS: 'TEAMS_DELETE_SUCCESS',
  DELETE_FAILURE: 'TEAMS_DELETE_FAILURE',

  INVALIDATE_TEAM_CACHE: 'INVALIDATE_TEAM_CACHE'
};
