export const ticketConstants = {

    GETPAGE_REQUEST: 'TICKETS_GETPAGE_REQUEST',
    GETPAGE_SUCCESS: 'TICKETS_GETPAGE_SUCCESS',
    GETPAGE_FAILURE: 'TICKETS_GETPAGE_FAILURE',

    GETPAGE_REQUEST_TARGET: 'GETPAGE_REQUEST_TARGET',
    GETPAGE_SUCCESS_TARGET: 'GETPAGE_SUCCESS_TARGET',
    GETPAGE_FAILURE_TARGET: 'GETPAGE_FAILURE_TARGET',

    GETPAGE_REQUEST_CATEGORY: 'GETPAGE_REQUEST_CATEGORY',
    GETPAGE_SUCCESS_CATEGORY: 'GETPAGE_SUCCESS_CATEGORY',
    GETPAGE_FAILURE_CATEGORY: 'GETPAGE_FAILURE_CATEGORY',

    INVALIDATE_TICKETS_CACHE: 'INVALIDATE_TICKETS_CACHE',

    INVALIDATE_TICKETS_PAGE_CACHE: 'INVALIDATE_TICKETS_PAGE_CACHE',
    INVALIDATE_TICKETS_PAGE_CACHE_TARGET: 'INVALIDATE_TICKETS_PAGE_CACHE_TARGET',
    INVALIDATE_TICKETS_PAGE_CACHE_CATEGORY: 'INVALIDATE_TICKETS_PAGE_CACHE_CATEGORY'
};
